ktor {
  deployment {
    port = 8080
  }

  application {
    modules = [ com.fairpay.ApplicationKt.module ]
  }
}

database {
  url = ${?DATABASE_URL}
  driver = "org.postgresql.Driver"
  user = ${?DATABASE_USER}
  password = ${?DATABASE_PASSWORD}
  maximumPoolSize = 10
}

jwt {
  secret = "super-secret-key-fairpay"
  issuer = "fairpay"
  audience = "fairpay-users"
  realm = "fairpay"
}